# -*- coding: utf-8 -*-
"""Currency_Converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m076iAUrmlwis-L-AJD65i6loWS406Y7
"""

import requests

def get_exchange_rate(base_currency, target_currency):
    api_url = f"https://api.exchangerate-api.com/v4/latest/{base_currency}"
    response = requests.get(api_url)
    data = response.json()

    if target_currency in data["rates"]:
        return data["rates"][target_currency]
    else:
        raise ValueError("Target currency not found in exchange rates data.")

def convert_currency(amount, exchange_rate):
    return amount * exchange_rate

def main():
    base_currency = input("Enter the base currency: ").upper()
    target_currency = input("Enter the target currency: ").upper()
    amount = float(input("Enter the amount: "))

    try:
        exchange_rate = get_exchange_rate(base_currency, target_currency)
        converted_amount = convert_currency(amount, exchange_rate)
        print(f"{amount} {base_currency} is equal to {converted_amount:.2f} {target_currency}")
    except ValueError as ve:
        print(ve)
    except requests.RequestException as re:
        print("An error occurred while fetching exchange rates:", re)
    except Exception as e:
        print("An error occurred:", e)

if __name__ == "__main__":
    main()