# -*- coding: utf-8 -*-
"""Word_Cloud_Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tH-O3yI2If7j9kz5PmzzdBYZVzfcYFZ_
"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

def generate_word_cloud(text):
    wordcloud = WordCloud(width=800, height=800, background_color='white', max_words=150).generate(text)
    plt.figure(figsize=(8, 8), facecolor=None)
    plt.imshow(wordcloud)
    plt.axis("off")
    plt.tight_layout(pad=0)
    plt.show()

def main():
    user_input = input("Enter the text for generating a word cloud: ")
    generate_word_cloud(user_input)

if __name__ == "__main__":
    main()